project:
  type: website
  output-dir: docs

website:
  title: "Fabian Kalleitner"
  site-url: https://fabiankal.github.io/personal_website_v2
  favicon: assets/favicon.ico
  navbar:
    title: "Fabian Kalleitner"
    right:
      - href: about.qmd
        text: About
      - href: publications.qmd
        text: Publications
      - href: projects.qmd
        text: Projects
      - href: teaching.qmd
        text: Teaching
      - text: CV
        href: https://syncandshare.lrz.de/dl/fi8HMRufYxqLvPfidtaNit/CV_Fabian_Kalleitner_eng.pdf?inline&skipCounter=true
    tools:
      - icon: github
        href: https://github.com/fabiankal
      - icon: envelope
        href: mailto:fabian.kalleitner@lmu.de
  page-footer:
    center: "© 2025 Fabian Kalleitner · Made with [Quarto](https://quarto.org)"
  comments: false

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: false
    link-external-icon: false
    link-external-newwindow: true
